name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Save SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Create deploy directory on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "mkdir -p ~/deploy"

      - name: Copy all necessary files to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no \
            -r BE ML docker-compose.yml ubuntu@${{ secrets.EC2_HOST }}:~/deploy/

      - name: SSH and deploy on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
            cd ~/deploy

            echo "${{ secrets.ENV_FILE }}" > .env

            docker compose down
            docker compose up -d --build
          EOF